import logging
import os
import subprocess
from typing import Dict, Any, List, Optional
from tools.tool_registry import tool_registry

logger = logging.getLogger("orian.developer_agent")

class DeveloperAgent:
    """Agent 4 — Developer Agent: Specialized coding assistant for file creation, refactoring, debugging, dependencies, testing, and deployment configs."""

    def __init__(self):
        self.agent_id = "DeveloperAgent"

    async def inspect_codebase(self, project_path: str) -> Dict[str, Any]:
        logger.info(f"[{self.agent_id}] Inspecting codebase at {project_path}")
        return await tool_registry.execute_tool("inspect_project", {"project_dir": project_path})

    async def generate_component_code(self, target_file: str, specification: str) -> Dict[str, Any]:
        logger.info(f"[{self.agent_id}] Generating code for {target_file}")
        
        # Simple boilerplate generation helper
        if target_file.endswith(".jsx") or target_file.endswith(".tsx"):
            code = (
                f"import React from 'react';\n\n"
                f"export default function GeneratedComponent() {{\n"
                f"  // {specification}\n"
                f"  return (\n"
                f"    <div className=\"p-4 bg-slate-900 text-white rounded-lg\">\n"
                f"      <h2 className=\"text-xl font-bold\">Orian Generated Component</h2>\n"
                f"      <p className=\"text-slate-400\">{specification}</p>\n"
                f"    </div>\n"
                f"  );\n"
                f"}}\n"
            )
        elif target_file.endswith(".py"):
            code = (
                f"# Generated by Orian AI Developer Agent\n"
                f"# Specification: {specification}\n\n"
                f"def run_generated_task():\n"
                f"    print('Running Orian Generated Task: {specification}')\n"
                f"    return True\n"
            )
        else:
            code = f"// Orian AI Generated File\n// Specification: {specification}\n"

        res = await tool_registry.execute_tool("write_file", {"file_path": target_file, "content": code})
        return res

    async def run_project_tests(self, project_path: str) -> Dict[str, Any]:
        logger.info(f"[{self.agent_id}] Running test suite at {project_path}")
        res = await tool_registry.execute_tool("run_terminal_command", {"command": "npm test", "cwd": project_path})
        return res

developer_agent = DeveloperAgent()
